#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

m4 system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
runApplication setFields

# mono proc
#runApplication $(getApplication)

# parallel
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

runApplication foamToVTK
#paraview /VTK*series &
#------------------------------------------------------------------------------
